name: Lint Grafana Dashboard

on:
  workflow_call:


jobs:
  lint-grafana:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install Grafana Dashboard Linter
        run: go install github.com/grafana/dashboard-linter@latest
      - name: Run Grafana Dashboard Lint
        run: dashboard-linter lint src/grafana_dashboards/* --strict -c grafana.lint